env:
  browser: true
  commonjs: true
  es6: true
  node: true
  webextensions: true
  jquery: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 2018
  ecmaFeatures:
    experimentalObjectRestSpread: true
    spread: true
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  eqeqeq:
    - error
    - always
